#include <fstream>
#include <iostream>
#include <string>

int main(int argc, char **argv) {
  if (argc < 3) {
    std::cout << "Invalid usage.\nUsage: " << argv[0] << " <fNameFile> <outFile>\n";
    return 1;
  }

  // Open output file.
  std::ofstream testFile(argv[2]);
  testFile << "#include \"tests/AllTests.h\"\n\n";
  testFile << "// Autogenerated tests file.\n";
  testFile << "void getAllTests(CuSuite *suite) {\n";

  // Read function names.
  std::ifstream fNames(argv[1]);
  std::string fName;
  fNames >> fName;
  while (fNames.good()) {
    testFile << "  SUITE_ADD_TEST(suite, " << fName << ");\n";
    fNames >> fName;
  }

  testFile << "}\n";
}
